SELECT EMP_ID,EMP_NAME,SALARY,JOB_NAME 
FROM EMPLOYEE JOIN JOB USING(JOB_CODE) 
ORDER BY SALARY DESC ;
SELECT EMP_ID,EMP_NAME,SALARY,JOB_NAME
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE SALARY>6000000
ORDER BY SALARY DESC;
SELECT EMP_ID,EMP_NAME,SALARY
FROM EMPLOYEE 
WHERE SALARY BETWEEN 1000000 AND 3000000
ORDER BY SALARY DESC
;
SELECT EMP_ID,EMP_NAME,DEPT_TITLE ,JOB_NAME
FROM EMPLOYEE JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID) JOIN JOB USING (JOB_CODE)
;


SELECT * FROM EMPLOYEE2;

--사번으로 사원 정보조회

SELECT  * FROM EMPLOYEE 
WHERE EMP_ID ='200';

--입력 받은 급여 이상으로 받는 모든 직원 조회

SELECT *FROM EMPLOYEE 
WHERE SALARY >4000000;

-- insert 9개


INSERT INTO EMPLOYEE2 VALUES(233,'홍길동','001212-1234567','HONG@kh.OR.kr',
'010-123-1234','D1','J1','S1',8000000,0.3,200,SYSDATE,NULL,'N');

DELETE FROM EMPLOYEE2 WHERE EMP_ID = 900;
SELECT * FROM EMPLOYEE2;
COMMIT;
ROLLBACK;


--UPDATE 테이블명 SET 컬럼명 = 바꿀값 [WHERE 컬럼명 비교연산자 비교값];

UPDATE EMPLOYEE2 SET EMAIL ='D', PHONE ='123',SALARY ='123' WHERE EMP_ID =233;

UPDATE DEPARTMENT2 
SET DEPT_TITLE ='전략기획팀'
WHERE DEPT_ID='D9';

UPDATE EMPLOYEE2 SET BONUS ='0.4' WHERE DEPT_CODE ='D9';