SELECT * FROM "COMMENT";
SELECT * FROM "BOARD";

SELECT * FROM "USER";


UPDATE "USER" SET 
MEMBER_NK=?
WHERE MEMBER_NO=?


SELECT MEMBER_PW 
FROM "USER"
WHERE MEMBER_NO =5;
SELECT * FROM CHALLENGE_BOARD ;
SELECT * FROM BOARD_TYPE ;
INSERT INTO "BOARD_TYPE"
VALUES(4,'공지사항게시판');
BEGIN
    FOR I IN 1..50 LOOP
    
        INSERT INTO BOARD
        VALUES(SEQ_BOARD_NO.NEXTVAL,
               SEQ_BOARD_NO.CURRVAL || '번째 게시글(공지사항)',
               SEQ_BOARD_NO.CURRVAL || '번째 게시글 내용입니다(-1).',
               DEFAULT, DEFAULT, DEFAULT, DEFAULT, 1, 4, -1
        );
    END LOOP;
END;
/;
INSERT INTO "COMMENT" VALUES(SEQ_RNO.NEXTVAL, '댓글 테스트3', DEFAULT, DEFAULT, 1, 1);
COMMIT;

INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, '물음표','물음표',DEFAULT,DEFAULT,DEFAULT,DEFAULT,1,1,-1);


UPDATE "USER" SET 
MANAGER_FL='Y'
WHERE MEMBER_NO=5;

UPDATE "COMMENT" SET
COMMENT_FL ='Y'
WHERE COMMENT_NO=1;

		SELECT SEQ_BOARD_NO.NEXTVAL
		FROM DUAL;
		
		
		UPDATE BOARD SET POST_ST='Y'
		WHERE BOARD_NO =274;
		
	COMMIT;