SELECT * FROM "COMMENT";
SELECT * FROM "BOARD";
SELECT * FROM "USER";
INSERT INTO "COMMENT" VALUES(SEQ_RNO.NEXTVAL, '댓글 테스트3', DEFAULT, DEFAULT, 1, 1);
COMMIT;

INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, '물음표','물음표',DEFAULT,DEFAULT,DEFAULT,DEFAULT,1,1,-1);




UPDATE "COMMENT" SET
COMMENT_FL ='Y'
WHERE COMMENT_NO=1;